highlighter: rouge
name: Arthur's Ramblings
description: Just some random things to blog about :)
url: "http://apstemmer.github.io"
lsi: false

permalink: pretty
theme: minima
markdown: kramdown

minima:
  social_links:
      github:  apstemmer